export const SETUP = "SETUP";
export const SETUP_REQUESTED = "SETUP_REQUESTED";
export const SETUP_SUCCEEDED = "SETUP_SUCCEEDED";
export const SETUP_FAILED = "SETUP_FAILED";

// sync actions
export const GENERATE_GRID = "GENERATE_GRID";
export const PATHS_CALCULATED = "PATHS_CALCULATED";

// actions for calculating paths
export const GENERATE_PATHS = "CALCULATE_PATHS";
export const GENERATE_PATHS_REQUESTED = "GENERATE_PATHS_REQUESTED";
export const GENERATE_PATHS_SUCCEEDED = "GENERATE_PATHS_SUCCEEDED";
export const GENERATE_PATHS_FAILED = "GENERATE_PATHS_FAILED";

// actions for visualization

export const RUN_VISUALIZATION = "RUN_VISUALIZATION";
export const RUN_VISUALIZATION_SUCCEEDED = "RUN_VISUALIZATION_SUCCEEDED";
export const RUN_VISUALIZATION_FAILED = "RUN_VISUALIZATION_FAILED";

export const VISUALIZE_PATH = "VISUALIZE_PATH";
export const VISUALIZE_PATH_REQUESTED = "VISUALIZE_PATH_REQUESTED";
export const VISUALIZE_PATH_SUCCEEDED = "VISUALIZE_PATH_SUCCEEDED";
export const VISUALIZE_PATH_FAILED = "VISUALIZE_PATH_FAILED";

export const VISUALIZE_STEP = "VISUALIZE_STEP";
