export const GENERATING_PATHS = "GENERATING_PATHS";
export const CALCULATE_PATHS = "CALCULATE_PATHS";

export const GENERATE_GRID = "GENERATE_GRID";
export const CLEAR_GRID = "CLEAR_GRID";
export const UPDATE_GRID = "UPDATE_GRID";
